//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 10:48:49 AM MESZ 
//


package dozenten;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dozenten package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dozenten
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Newsticker }
     * 
     */
    public Dozenten.Dozent.Newsticker createDozentenDozentNewsticker() {
        return new Dozenten.Dozent.Newsticker();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Adresse }
     * 
     */
    public Dozenten.Dozent.Adresse createDozentenDozentAdresse() {
        return new Dozenten.Dozent.Adresse();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Abonnenten.Abonnent }
     * 
     */
    public Dozenten.Dozent.Abonnenten.Abonnent createDozentenDozentAbonnentenAbonnent() {
        return new Dozenten.Dozent.Abonnenten.Abonnent();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Lehre.Veranstaltungen.List }
     * 
     */
    public Dozenten.Dozent.Lehre.Veranstaltungen.List createDozentenDozentLehreVeranstaltungenList() {
        return new Dozenten.Dozent.Lehre.Veranstaltungen.List();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Lehre }
     * 
     */
    public Dozenten.Dozent.Lehre createDozentenDozentLehre() {
        return new Dozenten.Dozent.Lehre();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Titel }
     * 
     */
    public Dozenten.Dozent.Titel createDozentenDozentTitel() {
        return new Dozenten.Dozent.Titel();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Lehre.Veranstaltungen }
     * 
     */
    public Dozenten.Dozent.Lehre.Veranstaltungen createDozentenDozentLehreVeranstaltungen() {
        return new Dozenten.Dozent.Lehre.Veranstaltungen();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Adresse.Tel }
     * 
     */
    public Dozenten.Dozent.Adresse.Tel createDozentenDozentAdresseTel() {
        return new Dozenten.Dozent.Adresse.Tel();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Adresse.Raum }
     * 
     */
    public Dozenten.Dozent.Adresse.Raum createDozentenDozentAdresseRaum() {
        return new Dozenten.Dozent.Adresse.Raum();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Adresse.Email }
     * 
     */
    public Dozenten.Dozent.Adresse.Email createDozentenDozentAdresseEmail() {
        return new Dozenten.Dozent.Adresse.Email();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Adresse.Tel.Nummer }
     * 
     */
    public Dozenten.Dozent.Adresse.Tel.Nummer createDozentenDozentAdresseTelNummer() {
        return new Dozenten.Dozent.Adresse.Tel.Nummer();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Abonnenten }
     * 
     */
    public Dozenten.Dozent.Abonnenten createDozentenDozentAbonnenten() {
        return new Dozenten.Dozent.Abonnenten();
    }

    /**
     * Create an instance of {@link Dozenten }
     * 
     */
    public Dozenten createDozenten() {
        return new Dozenten();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent.Newsticker.Eintrag }
     * 
     */
    public Dozenten.Dozent.Newsticker.Eintrag createDozentenDozentNewstickerEintrag() {
        return new Dozenten.Dozent.Newsticker.Eintrag();
    }

    /**
     * Create an instance of {@link Dozenten.Dozent }
     * 
     */
    public Dozenten.Dozent createDozentenDozent() {
        return new Dozenten.Dozent();
    }

}
