//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 07:29:09 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/dozent", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dozenten;
