//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 05:23:46 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/semester", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package semester;
