//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 05:23:46 PM MESZ 
//


package classSemester;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="semester">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="zeitpunkt">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="kuerzel" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="modulplan">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="modul" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dozent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="credits" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="aufwand" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="termin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "semester"
})
@XmlRootElement(name = "mi_semester")
public class MiSemester {

    @XmlElement(required = true)
    protected MiSemester.Semester semester;

    /**
     * Gets the value of the semester property.
     * 
     * @return
     *     possible object is
     *     {@link MiSemester.Semester }
     *     
     */
    public MiSemester.Semester getSemester() {
        return semester;
    }

    /**
     * Sets the value of the semester property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiSemester.Semester }
     *     
     */
    public void setSemester(MiSemester.Semester value) {
        this.semester = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="zeitpunkt">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="kuerzel" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="modulplan">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="modul" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="dozent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="credits" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="aufwand" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="termin" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zeitpunkt",
        "modulplan"
    })
    public static class Semester {

        @XmlElement(required = true)
        protected MiSemester.Semester.Zeitpunkt zeitpunkt;
        @XmlElement(required = true)
        protected MiSemester.Semester.Modulplan modulplan;

        /**
         * Gets the value of the zeitpunkt property.
         * 
         * @return
         *     possible object is
         *     {@link MiSemester.Semester.Zeitpunkt }
         *     
         */
        public MiSemester.Semester.Zeitpunkt getZeitpunkt() {
            return zeitpunkt;
        }

        /**
         * Sets the value of the zeitpunkt property.
         * 
         * @param value
         *     allowed object is
         *     {@link MiSemester.Semester.Zeitpunkt }
         *     
         */
        public void setZeitpunkt(MiSemester.Semester.Zeitpunkt value) {
            this.zeitpunkt = value;
        }

        /**
         * Gets the value of the modulplan property.
         * 
         * @return
         *     possible object is
         *     {@link MiSemester.Semester.Modulplan }
         *     
         */
        public MiSemester.Semester.Modulplan getModulplan() {
            return modulplan;
        }

        /**
         * Sets the value of the modulplan property.
         * 
         * @param value
         *     allowed object is
         *     {@link MiSemester.Semester.Modulplan }
         *     
         */
        public void setModulplan(MiSemester.Semester.Modulplan value) {
            this.modulplan = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="modul" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dozent" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="credits" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="aufwand" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="termin" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "modul"
        })
        public static class Modulplan {

            protected List<MiSemester.Semester.Modulplan.Modul> modul;

            /**
             * Gets the value of the modul property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the modul property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getModul().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MiSemester.Semester.Modulplan.Modul }
             * 
             * 
             */
            public List<MiSemester.Semester.Modulplan.Modul> getModul() {
                if (modul == null) {
                    modul = new ArrayList<MiSemester.Semester.Modulplan.Modul>();
                }
                return this.modul;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dozent" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="credits" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="aufwand" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="termin" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "titel",
                "dozent"
            })
            public static class Modul {

                @XmlElement(required = true)
                protected String titel;
                @XmlElement(required = true)
                protected String dozent;
                @XmlAttribute
                protected String credits;
                @XmlAttribute
                protected String aufwand;
                @XmlAttribute
                protected String termin;

                /**
                 * Gets the value of the titel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitel() {
                    return titel;
                }

                /**
                 * Sets the value of the titel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitel(String value) {
                    this.titel = value;
                }

                /**
                 * Gets the value of the dozent property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDozent() {
                    return dozent;
                }

                /**
                 * Sets the value of the dozent property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDozent(String value) {
                    this.dozent = value;
                }

                /**
                 * Gets the value of the credits property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCredits() {
                    return credits;
                }

                /**
                 * Sets the value of the credits property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCredits(String value) {
                    this.credits = value;
                }

                /**
                 * Gets the value of the aufwand property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAufwand() {
                    return aufwand;
                }

                /**
                 * Sets the value of the aufwand property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAufwand(String value) {
                    this.aufwand = value;
                }

                /**
                 * Gets the value of the termin property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTermin() {
                    return termin;
                }

                /**
                 * Sets the value of the termin property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTermin(String value) {
                    this.termin = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="kuerzel" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Zeitpunkt {

            @XmlValue
            protected String value;
            @XmlAttribute
            @XmlSchemaType(name = "anySimpleType")
            protected String kuerzel;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the kuerzel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKuerzel() {
                return kuerzel;
            }

            /**
             * Sets the value of the kuerzel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKuerzel(String value) {
                this.kuerzel = value;
            }

        }

    }

}
